services:
  - type: web
    name: reachable-website
    env: php
    buildCommand: "composer install --no-dev --optimize-autoloader"
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true