services:
  - type: web
    name: weblyme
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:cache
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:PLACEHOLDER  # هيتم توليدها تلقائيًا
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: reachable
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value:
